spring:
    thymeleaf:
        cache: false
    template:
        cache: false
    profiles:
      active: dev
---
spring:
  profiles: dev
  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./db/test
        username: sa
        password:
---
spring:
  profiles: heroku
  datasource:
        driverClassName: org.postgresql.Driver
        url: postgres://gklltqdsbmtciq:NiC5hEjrCvj-K3KWE8V2xW8uPR@ec2-23-21-167-249.compute-1.amazonaws.com:5432/d3q7dnfb7uf3o1/operation_board
        username: postgres
        password: yokuboga