spring:
    thymeleaf:
        cache: false
    profiles:
      active: dev
---
spring:
  profiles: dev
  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./db/test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
---
spring:
  profiles: heroku
  datasource:
        driverClassName: org.postgresql.Driver