spring:
    thymeleaf:
        cache: false
    profiles:
      active: dev
---
spring:
  profiles: dev
  datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:./db/test;MODE=PostgreSQL
        username: sa
        password:
---
spring:
  profiles: heroku
  datasource:
        driverClassName: org.postgresql.Driver
  jpa:
        database: POSTGRESQL
        hibernate:
          ddl-auto: create-drop